const SNIPPETS = {

// ===== BUTTONS (1–30) =====
button: `<button>Click me</button>`,
primary_button: `<button style="background:#2563eb;color:white;padding:10px 16px;border:none;border-radius:6px;">Primary</button>`,
secondary_button: `<button style="background:#64748b;color:white;padding:10px 16px;border:none;border-radius:6px;">Secondary</button>`,
red_button: `<button style="background:red;color:white;padding:10px 16px;border:none;border-radius:6px;">Delete</button>`,
green_button: `<button style="background:green;color:white;padding:10px 16px;border:none;border-radius:6px;">Confirm</button>`,
outline_button: `<button style="border:2px solid #2563eb;color:#2563eb;padding:10px 16px;background:none;">Outline</button>`,
icon_button: `<button>🔔</button>`,
disabled_button: `<button disabled>Disabled</button>`,
full_width_button: `<button style="width:100%;">Full width</button>`,
rounded_button: `<button style="border-radius:999px;padding:10px 20px;">Rounded</button>`,
loading_button: `<button>Loading...</button>`,
alert_button: `<button onclick="alert('Hello')">Alert</button>`,
submit_button: `<button type="submit">Submit</button>`,
reset_button: `<button type="reset">Reset</button>`,
link_button: `<a href="#">Link button</a>`,
toggle_button: `<button onclick="this.classList.toggle('active')">Toggle</button>`,
danger_button: `<button style="background:#b91c1c;color:white;">Danger</button>`,
success_button: `<button style="background:#16a34a;color:white;">Success</button>`,
info_button: `<button style="background:#0284c7;color:white;">Info</button>`,
light_button: `<button style="background:#f1f5f9;color:#111;">Light</button>`,
dark_button: `<button style="background:#111;color:white;">Dark</button>`,
icon_only_button: `<button>⭐</button>`,
submit_primary: `<button type="submit" style="background:#2563eb;color:white;">Submit</button>`,
reset_secondary: `<button type="reset" style="background:#64748b;color:white;">Reset</button>`,
rounded_primary: `<button style="border-radius:20px;background:#2563eb;color:white;">Rounded Primary</button>`,
small_button: `<button style="padding:5px 10px;">Small</button>`,
large_button: `<button style="padding:15px 30px;">Large</button>`,

// ===== INPUTS (31–60) =====
input_text: `<input type="text" placeholder="Text">`,
input_password: `<input type="password" placeholder="Password">`,
input_email: `<input type="email" placeholder="Email">`,
input_number: `<input type="number">`,
input_date: `<input type="date">`,
input_color: `<input type="color">`,
input_range: `<input type="range">`,
textarea: `<textarea placeholder="Write..."></textarea>`,
checkbox: `<label><input type="checkbox"> Checkbox</label>`,
radiobutton: `<label><input type="radio"> Radio</label>`,
select: `<select><option>A</option><option>B</option></select>`,
file_upload: `<input type="file">`,
search_input: `<input type="search" placeholder="Search">`,
readonly_input: `<input value="Read only" readonly>`,
disabled_input: `<input disabled>`,
phone_input: `<input type="tel" placeholder="Phone">`,
url_input: `<input type="url" placeholder="Website">`,
month_input: `<input type="month">`,
week_input: `<input type="week">`,
datalist_input: `<input list="browsers"><datalist id="browsers"><option>Chrome</option><option>Firefox</option></datalist>`,
input_search_icon: `<input type="search" placeholder="Search 🔍">`,
input_password_show: `<input type="password" placeholder="Password"> <button>Show</button>`,
number_spinner: `<input type="number" step="1" min="0">`,
slider_input: `<input type="range" min="0" max="100">`,
color_picker: `<input type="color" value="#ff0000">`,

// ===== TEXT & HEADINGS (61–90) =====
h1: `<h1>Heading 1</h1>`,
h2: `<h2>Heading 2</h2>`,
h3: `<h3>Heading 3</h3>`,
h4: `<h4>Heading 4</h4>`,
h5: `<h5>Heading 5</h5>`,
h6: `<h6>Heading 6</h6>`,
paragraph: `<p>Lorem ipsum dolor sit amet.</p>`,
small_text: `<small>Small text</small>`,
strong_text: `<strong>Bold text</strong>`,
em_text: `<em>Italic text</em>`,
blockquote: `<blockquote>Quote here</blockquote>`,
code_inline: `<code>inline code</code>`,
preformatted: `<pre>Preformatted</pre>`,
mark_text: `<mark>Highlighted</mark>`,
del_text: `<del>Deleted text</del>`,
ins_text: `<ins>Inserted text</ins>`,
sup_text: `<sup>Superscript</sup>`,
sub_text: `<sub>Subscript</sub>`,
highlight_yellow: `<span style="background:yellow;">Highlight</span>`,
highlight_blue: `<span style="background:lightblue;">Highlight</span>`,
underline_text: `<u>Underline</u>`,
italic_bold: `<strong><em>Bold Italic</em></strong>`,

// ===== LAYOUT & CONTAINERS (91–120) =====
container: `<div style="max-width:800px;margin:auto;">Container</div>`,
section: `<section>Section</section>`,
article: `<article>Article</article>`,
flex_row: `<div style="display:flex;gap:10px;"><div>A</div><div>B</div></div>`,
flex_column: `<div style="display:flex;flex-direction:column;">Column</div>`,
grid_2: `<div style="display:grid;grid-template-columns:1fr 1fr;">Grid</div>`,
grid_3: `<div style="display:grid;grid-template-columns:repeat(3,1fr);">Grid</div>`,
centered: `<div style="display:flex;align-items:center;justify-content:center;">Centered</div>`,
spacer: `<div style="height:40px;"></div>`,
divider: `<hr>`,
card: `<div style="border:1px solid #ccc;padding:16px;border-radius:8px;">Card</div>`,
panel: `<div style="background:#f1f5f9;padding:16px;">Panel</div>`,
hero: `<section style="padding:60px;background:#2563eb;color:white;">Hero</section>`,
sticky_header: `<header style="position:sticky;top:0;">Sticky</header>`,
footer_layout: `<footer>Footer</footer>`,
container_fluid: `<div style="width:100%;">Full width</div>`,
wrapper: `<div class="wrapper">Wrapper</div>`,
grid_responsive: `<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px;">Responsive</div>`,
grid_gap: `<div style="display:grid;grid-gap:20px;"><div>A</div><div>B</div></div>`,
flex_wrap: `<div style="display:flex;flex-wrap:wrap;"><div>1</div><div>2</div></div>`,
flex_justify: `<div style="display:flex;justify-content:space-between;"><div>Left</div><div>Right</div></div>`,

// ===== NAVIGATION & MENU (121–150) =====
navbar: `<nav><a>Home</a> <a>About</a> <a>Contact</a></nav>`,
breadcrumbs: `<nav>Home / Page</nav>`,
sidebar: `<aside>Sidebar</aside>`,
tabs: `<div>Tab 1 | Tab 2</div>`,
menu: `<ul><li>Item 1</li><li>Item 2</li></ul>`,
dropdown: `<select><option>Menu</option></select>`,
pagination: `<div>1 2 3</div>`,
mobile_nav: `<nav>☰ Menu</nav>`,
footer_nav: `<nav>Footer links</nav>`,
skip_link: `<a href="#main">Skip</a>`,
vertical_menu: `<ul><li>One</li><li>Two</li></ul>`,
hamburger_menu: `<div>☰</div>`,
top_navbar: `<nav style="position:fixed;top:0;width:100%;">Top nav</nav>`,
bottom_navbar: `<nav style="position:fixed;bottom:0;width:100%;">Bottom nav</nav>`,
side_nav: `<nav style="width:200px;float:left;">Sidebar</nav>`,

// ===== FORMS & FEEDBACK (151–200) =====
login_form: `<form>Login</form>`,
signup_form: `<form>Signup</form>`,
contact_form: `<form>Contact</form>`,
search_form: `<form>Search</form>`,
comment_box: `<textarea>Comment</textarea>`,
table: `<table><tr><td>A</td></tr></table>`,
alert_box: `<div style="background:yellow;">Alert</div>`,
error_box: `<div style="background:red;color:white;">Error</div>`,
success_box: `<div style="background:green;color:white;">Success</div>`,
info_box: `<div style="background:blue;color:white;">Info</div>`,
modal: `<div>Modal</div>`,
tooltip: `<span title="Tip">Hover</span>`,
spinner: `<div>Loading...</div>`,
progress: `<progress value="50" max="100"></progress>`,
badge: `<span>Badge</span>`,
tag: `<span>#tag</span>`,
notification_toast: `<div style="position:fixed;bottom:10px;right:10px;background:#333;color:white;padding:10px;border-radius:6px;">Toast</div>`,
loading_overlay: `<div style="position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,.5);">Loading...</div>`,
form_group: `<div class="form-group"><label>Name</label><input></div>`,
input_with_icon: `<div><input placeholder="Search"><span>🔍</span></div>`,
validation_error: `<div style="color:red;">Error message</div>`,
success_message: `<div style="color:green;">Success!</div>`,
checkbox_group: `<div><label><input type="checkbox"> One</label><label><input type="checkbox"> Two</label></div>`,
radio_group: `<div><label><input type="radio"> Option 1</label><label><input type="radio"> Option 2</label></div>`
};
